### ISSUE TITLE
Unusual lag with stuck mobs

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#165]
_From @claw4oo on August 30, 2018 8:54_

### Expected Behavior
N/A

### Actual Behavior
Animals that are stuck in water pools, naturally generated or not, cannot expect and lag quite a bit, using tickprofiler to find the problem

### Steps to Reproduce
Throw an animal, like a chicken, cow, sheep, or goat into a naturally generated pool that cannot be escaped without building out. Keep the chunk loaded for a while, and run a tick profiler to confirm it's the animal.

Moving the animal outside of the stuck area seems to fix the problem.

Unsure of how to reliable reproduce quickly.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.5.1.1
Server

### Screenshots encouraged
https://gyazo.com/f877704097715d3ca61ef4445f929ee7

_Copied from original issue: capnkirok/animania#637_

**Comment by Tschipp** [comment]
_From @capnkirok on August 30, 2018 9:7_

Thanks for the report. I thought I had addressed this, but will take another look.

**Comment by Tschipp** [comment]
_From @Deshiba on August 30, 2018 13:10_

Last I saw anything about this the problem was that animals walked into water pools with 2 high walls with natural gen. The solution then was to have their AI prevent going down in the hole on their own.

If they are forced in however, the original issue will still be the same.

**Comment by Tschipp** [comment]
_From @claw4oo on August 30, 2018 22:17_

Several versions back, I had this problem with chickens getting stuck in very odd places, sometimes I couldn't even find the chicken despite having the coordinates. Most of the chickens were around the spawn chunk.
I fixed this problem temporarily by bringing down natural chicken spawns, and killing all already existing chickens in the map.

**Comment by Tschipp** [comment]
_From @claw4oo on August 31, 2018 4:4_

https://gyazo.com/ff0dde929ce8d926cdbad0c1c36aad85
Got a new picture confirming this.

https://gyazo.com/6900bdec7baa973794b94657ce42404d
This is with the problem fixed.

**Comment by capnkirok** [comment]
Looks like they still go in water when they can't get out.

**Comment by Tschipp** [comment]
Is this still an issue?

**Comment by Tschipp** [comment]
Going to close this, feel free to comment if this is still an issue.

**Comment by claw4oo** [comment]
It appears as the problem is happening once more to the server, where filled over water pools, filled with animania mobs causes a drop in performance, however it's harder to notice now that my server is starting to fill up those pools and culling the animals more often.

It also appears some nearby animals stuck ontop of ice seem to be eating up a bit of the performance as well sometimes. About 4-5 animals are ontop of hte ice on the second screenshot, checked it by the chunk.

I found this specific buried pool, by checking the chunk and how much performance it is demanding with the TickProfiler mod.

Checked it using the "/profile e" several times to confirm its this chunk.
A quick possible solution might be to kill mobs that have been bouncing ontop of water for a long period of time.

As a side note, there used to be a seasons mod that changed water to ice, and eventually melts it away over time.

It appears that overall though, Animania seems to demand a lot of the server's performance to keep going, maybe add an option to use a version that checks for updates far less, or be dependent on player radius/mob density.


Sorry for the late find.

Minecraft 1.12.2
animania-1.12.2-1.6.2
Serverside issue

https://gyazo.com/2e1f30c16a5374a9b1eb180f00b8d266
https://gyazo.com/db909f22d69c2c963e83fe5e7ecd492f
https://gyazo.com/505d4163045ee3889a7a067296db853c
