### ISSUE TITLE
animals dont use  trough

### ISSUE THREAD

**Issue by Alonlystalker** [capnkirok/animaniamod#300]
### Expected Behavior
Animals eat and drink from trough when they need to.

### Actual Behavior
Animals starve and thirst but still dont eat\drink from trunks

### Steps to Reproduce
place trough and animal near it

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.6.2, server

### Screenshots encouraged
![изображение](https://user-images.githubusercontent.com/1726962/54341229-6951bf00-464a-11e9-8060-9310531b7d17.png)

**Comment by RedOptic** [comment]
Im having the same issue on my server even with water source blocks 
![Inked2019-04-06_22 53 51_LI](https://user-images.githubusercontent.com/7763042/55684559-2a95e880-591a-11e9-8d8b-7425c4a7b6ca.jpg)

**Comment by Graywaren** [comment]
Same here as well with troughs

**Comment by Graywaren** [comment]
They'll often go and stand on them and spin around, but they'll stand there for ages and never drink

**Comment by Graywaren** [comment]
Any ideas on what could be causing this or how to fix it? Having just put a ton of effort into setting up a whole piping system for feeding and watering my animals to create automated farming, having the animals not use the troughs grinds everything to a halt. 

It doesn't seem to be 100% consistent though as I will sometimes get an animal that does use the trough, but it's as though 95% of the time they don't know it's there. They walk into it and stand in it, they interact with each other in it... but almost never actually use it. Could it somehow be that it is going invisible to their AI? Something else I noticed is that it could be related to the animals that are standing in it blocking it as a useable source, since if I move the animal(s) standing in the trough sometimes that will lead to other animals using it in the next minute or so until once again a couple sheep are standing in the trough again. I'm not entirely sure they can move out of it on their own without being pushed by another entity or picking them up with carryon etc.

More experimenting... it seems they are much better at using the trough if it is not up against other blocks and often their drinking animation is the blocks surrounding the trough while they stand in the trough rather than the other way around. I've had a full trough in a corner of a stall for hours with thirsty sheep. I moved it to the center of the stall and they more consistently use it by walking into it and animating drinking in the block past it. It might have to do with the ends of the trough not being against a block as opposed to a long side, since even moving it a block out of the corner so that each end had 1+ block of space made the animals more consistently be able to use it. Also they seem to have an easier time shortly after placing the trough as opposed to it having been there for minutes. I'm unsure if this is related to animals getting stuck standing in the trough though.... 

Can also confirm that this problem is happening with all water/food sources. Seems like it's some sort of pathing issue? Animals also have problems with water sources in ground, grass etc. Really frustrating. Not sure what happened since previously I've had animals feeding themselves work just fine. Will report back if I manage to figure anything else out.

**Comment by Sluggasaurus** [comment]
Also experiencing animals just standing on troughs instead of using them. The chicken seems to be the only animal that doesn't have this happen, could it be because they are only 1 block in size?

**Comment by edenhack** [comment]
I tried placing the trough in the ground and it seems to slightly resolve this issue with them not using the item.

**Comment by capnkirok** [comment]
I've updated the AI to be more forgiving. Entity centers and block centers are very strange. See next release.
