### ISSUE TITLE
server lagging to the point of crashing.

### ISSUE THREAD

**Issue by mindcloud69** [capnkirok/animaniamod#359]
## Actual Behavior
I believe that the Ai updates in 1.7.0 are causing a severe lag that is causing my server to crash.
I profiled the server during one of these hangs and it seams to me that the animania ai functions are eating up cpu resources. 

I created a flight recording on my server with jmx in the jdk so you can take a look.
[jmx](https://drive.google.com/file/d/1-vAXwNi1KN0NzKEmHblnH3n8VKs5b6A6/view?usp=sharing)

### Steps to Reproduce
move around an area with a lot of animals. It seem to happen when looking at trees a lot.

### Version of Minecraft, version of Animania, Single Player or Server
I am running the mod pack
dungeons dragons and space shuttles 6.0b

MC 1.12.2
animania 1.7.2
server
[Crash log](https://gist.github.com/mindcloud69/96760f253ad91fcd16e775be4d738804)

**Comment by katubug** [comment]
@mindcloud69 You're correct that the server crashed because the watchdog detected a high amount of lag. Your log mentions this crash report: `/minecraft/dnd/./crash-reports/crash-2019-09-29_22.04.40-server.txt` - Would you be able to upload that file to github/pastebin etc so that we can see more diagnostic information? What would also be helpful would be if you could do `/forge entity list` when things are feeling laggy, and then upload your `/logs/latest.log` from the server, so we can have a look at what animals are currently active.

Finally, I personally am not sure how to open your jmx file, but if you use a server profiling tool like the ones on [this page](https://www.reddit.com/r/allthemods/comments/9ugu6s/server_profiling/) (I recommend Spark as it's the easiest to use), it will give you more granular info on what in your world is taking up the most resources.

**Comment by mindcloud69** [comment]
I am sorry I have been busy with IRL responsibilities. I will attempt to get you the requested logs soon. The profiling tool I used comes with the Oracle JDK. You can find the JMX executable in you jdk bin dir. Then it is just a matter of file and open if you want to look at it. 

edit: I just double checked, the executable is jmc or jmc.exe in windows "java mission control"

**Comment by Tschipp** [comment]
Since this was on version 1.7.0 and many performance improvements have happened since then, I will consider this one as fixed and close it.
