### ISSUE TITLE
Mob is trying to access an invalid trough, throws NPE

### ISSUE THREAD

**Issue by NotMyWing** [capnkirok/animaniamod#368]
### Expected Behavior
The server should not crash. :p

https://github.com/capnkirok/animaniamod/blob/640f0a217cb786bc6e10dc65987c2773dacf0cbc/src/main/java/com/animania/common/tileentities/TileEntityInvisiblock.java#L132

This line, among several other lines, should check if `getTrough()` returned a valid tile-entity.

### Actual Behavior
A mob crashes the server by finding an invisiblock that has no paired trough block.

### Steps to Reproduce
...happen to break a Trough and leave its paired invisible block behind?

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.7.2, server.

### Crashlog
[crash-2019-10-08_23.50.32-server.txt](https://github.com/capnkirok/animaniamod/files/3702597/crash-2019-10-08_23.50.32-server.txt)

Thanks!

**Comment by vintrove** [comment]
I was able to recreate this a few times. It seems to be due to the carry-on mod incorrectly picking up empty troughs. It creates an image of wheat, calls the item in your hand "air" and when you place it back down it creates an invisible entity with collision. When a nearby animal comes looking for the invisible trough's contents it seems to crashes. ( I think )

[crash-2019-10-22_09.41.35-server.txt](https://github.com/capnkirok/animaniamod/files/3757438/crash-2019-10-22_09.41.35-server.txt)
[crash-2019-10-22_09.42.37-server.txt](https://github.com/capnkirok/animaniamod/files/3757439/crash-2019-10-22_09.42.37-server.txt)
[crash-2019-10-22_10.09.38-server.txt](https://github.com/capnkirok/animaniamod/files/3757440/crash-2019-10-22_10.09.38-server.txt)
![image](https://user-images.githubusercontent.com/37943945/67313218-79226300-f4b7-11e9-9913-9adae8666057.png)

**Comment by vintrove** [comment]
![image](https://user-images.githubusercontent.com/37943945/67313571-0960a800-f4b8-11e9-9f37-c72b65a19f99.png)
