### ISSUE TITLE
[Suggestion] More benefits for raising animals

### ISSUE THREAD

**Issue by CalaMariGold** [capnkirok/animaniamod#392]
Something my users noted in my modpack is that, for how difficult it is to raise animals, there doesn't seem to be much of a point, other than wanting to and enjoying the gameplay of it. But, I think it could use a little more incentive other than providing leather and feathers. Of course, you do it for food most of the time, but that is not enough as there are plenty of easier ways to obtain food.

A few ideas are obtaining more items for animals that are happy, fed, and breeding. Maybe animals provide better food when they have a straw bed, trough, nest, etc.... (would need compatibility with HarvestCraft)

Another idea is to give the player a potion buff when they have a certain amount of happy animals near them, or when they've fed enough animals, etc...

I'm sure I could ask my modpack users for more ideas, but this is what we have at the minute.

Thank you and I hope you consider!

**Comment by dibidibidisdan** [comment]
I'd like to see this! I like the ideas you've mentioned so far.

**Comment by frewmack** [comment]
I think that a good incentive would be for animals to drop XP from shearing, milking, butchering, etc. that's proportional to the animal's "happiness level".  Happier animals -> more XP.  This would be a strong incentive for players to raise livestock, especially more peaceful players whose only other XP source is mining.

**Comment by Tschipp** [comment]
So, here's the thing: Some parts of the mod are left like this intentionally. Not everything needs to be able to be "used" for many things. Just "having" a more realistic version of vanilla animals and augmenting gameplay around that should also be worth something, should it not? Animania isn't supposed to be like vanilla. It definitely is harder than vanilla and you have to take more care to manage your animals and feed them etc. This is intentional. We *do* offer a benefit of owning different breeds of animals though, as can be seen with different meat/milk products, but the focus of having the animals shouldn't be "how can I most efficiently exploit this". I understand that automation and making factories is fun, but even then, animania *does* allow for automation of certain processes. It's just... different from vanilla.

Yes, maybe we can offer more incentives for keeping the animals. But some animals, like frogs are just supposed to be ambient creatures. And that's fine. The fact that they even drop something should be redundant, but here we are I guess.

I like the idea of adding more features that doesn't involve just slaughtering the animals (such as more/different drops). Maybe keeping certain animals could increase growth speed of plants nearby? These are all possibilities, but we want to avoid adding more reasons to kill every animal you see.

**Comment by CalaMariGold** [comment]
I totally agree! I didn't mean to suggest more incentive to kill them, that's the last thing I'd want. But more incentive to *keep* them. I like the EXP idea for shearing and milking. Maybe animals drop EXP randomly when they're happy and are properly taken care of! There are so many possibilities for this. I understand the intention of just having a more realistic version of animals, but then again, this is still Minecraft. Players *need* a reason to do something. 90% of players are always going to go for the easiest route possible. And it's such a damn shame that most players really overlook the livestock aspect of Minecraft when this mod is installed in modpacks. I want more players to experience the beauty of it, but they need a reason to do so other than they just like to do it.
