### ISSUE TITLE
Bugs with finding truffles

### ISSUE THREAD

**Issue by Pultex** [capnkirok/animaniamod#393]
### Expected Behavior
Find Truffle in at least one day
with Hog or Sow

### Actual Behavior
Spend 2 days in game time looking for truffle
[4 days tried with both type of one species]
found nothing

### Steps to Reproduce
take hog or sow [tried both] into forest
spend 2 days looking for truffles with lead
get nothing

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft:1.12.2
Animania:animania-1.12.2-1.7.3
 also
BiomesOPlenty-1.12.2-7.0.1.2443-universal

More info:

BiomesOPlenty changes all forests to seasonal forests
If you have a map mod or the natures compass they see the forest then it changes when you arrive
I looked at other guides and Truffles HAVE to be forest so maybe the BiomesOPlenty Forests do not register with the mod.
I can find any Vanilla Forests

**Comment by Tschipp** [comment]
![image](https://user-images.githubusercontent.com/11649893/80913014-7c898780-8d41-11ea-85b6-ac86a05e3ba3.png)
While the truffle searching works, it is poorly described in the manual. The pigs actually need to be hungry in order to find anything (because they only dig if they're hungry). This caused me to find another bug though, as you can see from my inventory... oops (this was from one dig)
