### ISSUE TITLE
[Crash] Carrying hamster crashes with NamePain

### ISSUE THREAD

**Issue by democat3457** [capnkirok/animaniamod#468]
### Expected Behavior
For the hamster to not crash.

### Actual Behavior
Carrying the hamster crashes the game and the world is not loadable

### Steps to Reproduce
1. Carry a hamster on your shoulder.
2. Log out of the game
3. Be unable to log back in

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Animania: 1.7.3 (know it's old, couldn't update Animania because it'd break too many configs)
Name Pain: 1.2.1
SP or MP: SP

### Crash log, latest.log
[crash-2020-11-12_11.22.17-client.txt](https://github.com/capnkirok/animaniamod/files/5532459/crash-2020-11-12_11.22.17-client.txt)

Original issue: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/508

**Comment by Tschipp** [comment]
I don't know what NamePain does exactly as they seem to be closed source, but they probably call `getDistanceSq(BlockPos)` with a BlockPos that is null, or something along those lines. In any case, this is not an Animania bug, but on their end.

**Comment by naqaden** [comment]
I guess this wasn't opened on Name Pain, but I'll look into it, assuming NP 1.3 didn't already fix it.

**Comment by democat3457** [comment]
Well, we removed name pain anyway since we were able to hide vanilla nameplates using RotNTweaker (and name pain was redundant then)

**Comment by naqaden** [comment]
Yep I saw - seems like a better way to go for your needs. Of course I would still want this fixed for other NP users :)

**Comment by naqaden** [comment]
> 
> 
> I don't know what NamePain does exactly as they seem to be closed source, but they probably call `getDistanceSq(BlockPos)` with a BlockPos that is null, or something along those lines. In any case, this is not an Animania bug, but on their end.

We can see from the crash log that getDistanceSq(Entity) is called, rather than a getDistanceSq(BlockPos).

`java.lang.NullPointerException at net.minecraft.entity.Entity.getDistanceSq(Entity.java:1462)`

That entity (the hamster) came through RenderLivingEvent.Specials.Pre as null. However, I wasn't able to reproduce this issue with just Name Pain and Animania.

A [similar issue](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/521) clued me into adding Carry On to the mix. I'm opening an issue there with more detail. It's worth noting here though that the same test with a vanilla parrot does not cause the crash.

**Comment by democat3457** [comment]
We really gotta love three-way mod crashes
