### ISSUE TITLE
[FEATURE REQUEST] Thaumcraft aspects on content from this mod

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#52]
Now that Thauimcraft is on 1.12.2, would it be possible to add aspects onto content from this mod into it?

**Comment by iobiarg** [comment]
yes pls, i had to put vainilla mobs againg to advance in tc6 and i hate them... i want only animalia but tc6 aspects arent there

**Comment by Sunconure11** [comment]
Why not ping the contributors of this mod? @capnkirok @Tschipp 

Granted, I'm capable of it, but I'm involved in quite a few projects.

**Comment by Tschipp** [comment]
Yeah I’m sure we can do that

**Comment by DoomRater** [comment]
The bigger problem with advancing in TC6 is getting triple meat treat.  The souped up drops from Animania don't produce the necessary nuggets in the Infernal Furnace.  I went ahead and added them myself but it'd be nice to see that added officially too.

I'd do aspects too but holy god 150+ entities to add aspects for by hand.  It was painful enough adding them to the Roots Pacifist list and I had to finally write an AutoHotKey shortcut to automate the process or I would have been doing it for half an hour.

**Comment by Tschipp** [comment]
This is still on the TO-DO list, just like JourneyMap integration... we just haven't had the time...

**Comment by DoomRater** [comment]
Last night I sat down and decided to try and hammer in as many aspects as I could, and here's what I added via CraftTweaker: https://pastebin.com/W3CWM7Rh

Unfortunately, I guess Thaumic Additions wants more information than just aspects for its entity spawner because even adding aspects doesn't make it possible to capture them with entity cells.  Also I appear to have added the aspects in reverse order.
