### ISSUE TITLE
Question about Spawn Probability.

### ISSUE THREAD

**Issue by Rsslone** [capnkirok/animaniamod#67]
Does a higher probability number mean more spawns or less? How does it do its calculations? Is it 1/X chunks will spawn an animal?

Recommend specifying in the config comments what this means.

**Comment by capnkirok** [comment]
It uses the same calculation as vanilla MC spawn:
https://minecraft.gamepedia.com/Spawn#Mob_spawning

Basically, if the mob can spawn in a particular chunk (and time is correct, land is solid, correct biome, etc.), then it executes a probability roll to spawn. 

Plains have very few limitations, that's why there's always more spawns there. Whereas jungles and oceans have very little ground area, so spawning is less.

The higher the number, the higher the probability of spawning.
